variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - build
  - test
  - package
  - publish
  - release

build:ubuntu:
  stage: build
  tags:
    - ubuntu
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_PACKAGE=ON -DCPACK_BINARY_IFW=OFF -DCPACK_BINARY_STGZ=OFF -DBUILD_TESTING=ON -DENABLE_MODELICA_COMPILER=OFF  ..
    - cmake ..
    - make -j1
  artifacts:
    expire_in: 6 hrs
    paths:
      - build/

test:ubuntu:
  stage: test
  tags:
    - ubuntu
  dependencies:
    - build:ubuntu
  script:
    - cd build
    - ctest -R  unittests
  artifacts:
    expire_in: 6 hrs
    paths:
      - build/

package:ubuntu:
  stage: package
  tags:
    - ubuntu
  dependencies:
    - test:ubuntu
  script:
    - cd build
    - make package
  artifacts:
    expire_in: 6 hrs
    paths:
      - build/Spawn*.tar.gz

publish:ubuntu:
  stage: publish
  tags:
    - ubuntu
  dependencies:
    - package:ubuntu
  script:
    - python3 cmake/publish.py publish
  when: manual

release:ubuntu:
  stage: release
  tags:
    - ubuntu
  dependencies:
    - package:ubuntu
  script:
    - python3 cmake/publish.py release
  when: manual
  only:
    - tags

build:windows:
 stage: build
 tags:
   - windows
 script:
   - conan --version
   - pip3 --version
   - pip3 install -U conan
   - echo $env:PATH
   - $env:PATH = "c:\windows\system32\config\systemprofile\appdata\roaming\python\python37\Scripts;$env:PATH"
   - echo $env:PATH
   - dir c:\windows\system32\config\systemprofile\appdata\roaming\python\python37\Scripts
   - conan --version
   - mkdir build
   - cd build
   - C:\Program` Files\CMake\bin\cmake.exe -G 'Visual Studio 15 2017 Win64' -DBUILD_PACKAGE=ON -DCPACK_BINARY_ZIP=ON -DCPACK_BINARY_NSIS=OFF -DCPACK_BINARY_IFW=OFF -DBUILD_TESTING=ON ..
   - C:\Program` Files\CMake\bin\cmake.exe ..
   - C:\Program` Files\CMake\bin\cmake.exe --build . --config Release --target ALL_BUILD
 artifacts:
   expire_in: 6 hrs
   paths:
     - build/

test:windows:
  stage: test
  tags:
    - windows
  dependencies:
    - build:windows
  script:
    - cd build
    - C:\Program` Files\CMake\bin\ctest.exe -R unittests
  artifacts:
    expire_in: 6 hrs
    paths:
      - build/

package:windows:
  stage: package
  tags:
    - windows
  dependencies:
    - test:windows
  script:
    - cd build
    - C:\Program` Files\CMake\bin\cmake.exe --build . --config Release --target Package
  artifacts:
    expire_in: 6 hrs
    paths:
      - build/Spawn*.zip

publish:windows:
  stage: publish
  tags:
    - windows
  dependencies:
    - package:windows
  script:
    - python3 cmake/publish.py publish
  when: manual

release:windows:
  stage: release
  tags:
    - windows
  dependencies:
    - package:windows
  script:
    - python3 cmake/publish.py release
  when: manual
  only:
    - tags

build:mac:
 stage: build
 tags:
   - mac
 script:
   - which conan && conan --version
   - which pip3 && pip3 --version || pip --version
   - which pip3 && pip3 install --user -U conan || pip install --user -U conan
   - which conan && conan --version
   - mkdir build
   - cd build
   - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_PACKAGE=ON -DCPACK_BINARY_STGZ=OFF -DCPACK_BINARY_IFW=OFF -DBUILD_TESTING=ON ..
   - cmake ..
   - make -j2
 artifacts:
   expire_in: 6 hrs
   paths:
     - build/

test:mac:
  stage: test
  tags:
    - mac
  dependencies:
    - build:mac
  script:
    - cd build
    - ctest -R unittests
  artifacts:
    expire_in: 6 hrs
    paths:
      - build/

package:mac:
  stage: package
  tags:
    - mac
  dependencies:
    - test:mac
  script:
    - cd build
    - make package
  artifacts:
    expire_in: 6 hrs
    paths:
      - build/Spawn*.tar.gz

publish:mac:
  stage: publish
  tags:
    - mac
  dependencies:
    - package:mac
  script:
    - python3 cmake/publish.py publish
  when: manual

release:mac:
  stage: release
  tags:
    - mac
  dependencies:
    - package:mac
  script:
    - python3 cmake/publish.py release
  when: manual
  only:
    - tags
