variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - build
  - package
  - publish
  - release

build:ubuntu:
  stage: build
  tags:
    - ubuntu
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_PACKAGE=ON -DCPACK_BINARY_STGZ=OFF -DBUILD_TESTING=ON  ..
    - cmake ..
    - make -j2
  artifacts:
    expire_in: 6 hrs
    paths:
      - build/

package:ubuntu:
  stage: package
  tags:
    - ubuntu
  dependencies:
    - build:ubuntu
  script:
    - cd build
    - make package
  artifacts:
    expire_in: 6 hrs
    paths:
      - build/Spawn*.tar.gz

publish:ubuntu:
  stage: publish
  tags:
    - ubuntu
  dependencies:
    - package:ubuntu
  script:
    - python3 cmake/publish.py publish
  when: manual

release:ubuntu:
  stage: release
  tags:
    - ubuntu
  dependencies:
    - package:ubuntu
  script:
    - python3 cmake/publish.py release
  when: manual
  only:
    - tags

#build:windows:
#  stage: build
#  tags:
#    - windows
#  #before_script:
#  #  - set PATH=%PATH:C:\Program Files\Git\bin;=%
#  script:
#    - mkdir build
#    - cd build
#    - '"C:\Program Files\CMake\bin\cmake.exe" -G "Visual Studio 15 2017 Win64" -DBUILD_PACKAGE=ON -DCPACK_BINARY_ZIP=ON -DCPACK_BINARY_NSIS=OFF -DBUILD_TESTING=ON ..'
#    - '"C:\Program Files\CMake\bin\cmake.exe" ..'
#    - '"C:\Program Files\CMake\bin\cmake.exe" --build . --config Release --target ALL_BUILD'
#  artifacts:
#    expire_in: 6 hrs
#    paths:
#      - build/
#
#package:windows:
#  stage: package
#  tags:
#    - windows
#  dependencies:
#    - build:windows
#  script:
#    - cd build
#    - '"C:\Program Files\CMake\bin\cmake.exe" --build . --config Release --target Package'
#  artifacts:
#    expire_in: 6 hrs
#    paths:
#      - build/Spawn*.zip
#
#build:mac:
#  stage: build
#  tags:
#    - mac
#  script:
#    - mkdir build
#    - cd build
#    - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_PACKAGE=ON -DCPACK_BINARY_STGZ=OFF -DBUILD_TESTING=ON  ..
#    - cmake ..
#    - make -j4 Ipopt || true
#    - make -j4 Ipopt
#    - make -j4
#  artifacts:
#    expire_in: 6 hrs
#    paths:
#      - build/
#
#package:mac:
#  stage: package
#  tags:
#    - mac
#  dependencies:
#    - build:mac
#  script:
#    - cd build
#    - make package
#  artifacts:
#    expire_in: 6 hrs
#    paths:
#      - build/Spawn*.tar.gz

## Ubuntu 16.04 EnergyPlus packages are currently failing
#package:ubuntu:
#  stage: package
#  tags:
#    - ubuntu
#  dependencies:
#    - build:ubuntu
#  script:
#    - cd build
#    - make package -j
#  artifacts:
#    expire_in: 1 week
#    paths:
#      - build/EnergyPlus-*.sh

