variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - build
#  - package

build:ubuntu:
  stage: build
  tags:
    - ubuntu
  script:
    - mkdir build
    - cd build
    - cmake -DBUILD_PACKAGE=OFF  ..
    - cmake ..
    - make -j2
  artifacts:
    expire_in: 6 hrs
    paths:
      - build/

build:windows:
  stage: build
  tags:
    - windows
  before_script:
    - set PATH=%PATH:C:\Program Files\Git\bin;=%
  script:
    - mkdir build
    - cd build
    - '"C:\Program Files\CMake\bin\cmake.exe" -G "Visual Studio 15 2017 Win64"
    - '"C:\Program Files\CMake\bin\cmake.exe" ..'
    - '"C:\Program Files\CMake\bin\cmake.exe" --build . --config Release --target ALL_BUILD'
  artifacts:
    expire_in: 6 hrs
    paths:
      - build/

## Ubuntu 16.04 EnergyPlus packages are currently failing
#package:ubuntu:
#  stage: package
#  tags:
#    - ubuntu
#  dependencies:
#    - build:ubuntu
#  script:
#    - cd build
#    - make package -j
#  artifacts:
#    expire_in: 1 week
#    paths:
#      - build/EnergyPlus-*.sh

