#include "units.hpp"
#include <map>

struct OutputProperties {
	OutputProperties() = delete;

	spawn::units::UnitType moUnitType;
	spawn::units::UnitType epUnitType;
};

const std::map<const char *, OutputProperties> outputtypes {
	{"Site Outdoor Air Drybulb Temperature",{spawn::units::UnitType::K, spawn::units::UnitType::C}},
  {"Site Outdoor Air Dewpoint Temperature",{spawn::units::UnitType::K, spawn::units::UnitType::C}},
  {"Site Outdoor Air Wetbulb Temperature",{spawn::units::UnitType::K, spawn::units::UnitType::C}},
  {"Site Outdoor Air Humidity Ratio",{spawn::units::UnitType::one, spawn::units::UnitType::kgWater_per_kgDryAir}},
  {"Site Outdoor Air Relative Humidity",{spawn::units::UnitType::one, spawn::units::UnitType::percent}},
  {"Site Outdoor Air Barometric Pressure",{spawn::units::UnitType::Pa, spawn::units::UnitType::Pa}},
  {"Site Wind Speed",{spawn::units::UnitType::m_per_s, spawn::units::UnitType::m_per_s}},
  {"Site Wind Direction",{spawn::units::UnitType::rad, spawn::units::UnitType::deg}},
  {"Site Sky Temperature",{spawn::units::UnitType::K, spawn::units::UnitType::C}},
  {"Site Horizontal Infrared Radiation Rate per Area",{spawn::units::UnitType::W_per_m2, spawn::units::UnitType::W_per_m2}},
  {"Site Diffuse Solar Radiation Rate per Area",{spawn::units::UnitType::W_per_m2, spawn::units::UnitType::W_per_m2}},
  {"Site Direct Solar Radiation Rate per Area",{spawn::units::UnitType::W_per_m2, spawn::units::UnitType::W_per_m2}},
  {"Site Precipitation Depth",{spawn::units::UnitType::m, spawn::units::UnitType::m}},
  {"Site Ground Reflected Solar Radiation Rate per Area",{spawn::units::UnitType::W_per_m2, spawn::units::UnitType::W_per_m2}},
  {"Site Ground Temperature",{spawn::units::UnitType::K, spawn::units::UnitType::C}},
  {"Site Surface Ground Temperature",{spawn::units::UnitType::K, spawn::units::UnitType::C}},
  {"Site Deep Ground Temperature",{spawn::units::UnitType::K, spawn::units::UnitType::C}},
  {"Site Simple Factor Model Ground Temperature",{spawn::units::UnitType::K, spawn::units::UnitType::C}},
  {"Site Outdoor Air Enthalpy",{spawn::units::UnitType::J_per_kg, spawn::units::UnitType::J_per_kg}},
  {"Site Outdoor Air Density",{spawn::units::UnitType::kg_per_m3, spawn::units::UnitType::kg_per_m3}},
  {"Site Solar Azimuth Angle",{spawn::units::UnitType::rad, spawn::units::UnitType::deg}},
  {"Site Solar Altitude Angle",{spawn::units::UnitType::rad, spawn::units::UnitType::deg}},
  {"Site Solar Hour Angle",{spawn::units::UnitType::rad, spawn::units::UnitType::deg}},
  {"Site Rain Status",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Site Snow on Ground Status",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Site Exterior Horizontal Sky Illuminance",{spawn::units::UnitType::lm_per_m2, spawn::units::UnitType::lux}},
  {"Site Exterior Horizontal Beam Illuminance",{spawn::units::UnitType::lm_per_m2, spawn::units::UnitType::lux}},
  {"Site Exterior Beam Normal Illuminance",{spawn::units::UnitType::lm_per_m2, spawn::units::UnitType::lux}},
  {"Site Sky Diffuse Solar Radiation Luminous Efficacy",{spawn::units::UnitType::lm_per_W, spawn::units::UnitType::lm_per_W}},
  {"Site Beam Solar Radiation Luminous Efficacy",{spawn::units::UnitType::lm_per_W, spawn::units::UnitType::lm_per_W}},
  {"Site Daylighting Model Sky Clearness",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Site Daylighting Model Sky Brightness",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Site Daylight Saving Time Status",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Site Day Type Index",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Site Mains Water Temperature",{spawn::units::UnitType::K, spawn::units::UnitType::C}},
  {"Exterior Lights Electric Power",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Exterior Lights Electric Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Zone Outdoor Air Drybulb Temperature",{spawn::units::UnitType::K, spawn::units::UnitType::C}},
  {"Zone Outdoor Air Wetbulb Temperature",{spawn::units::UnitType::K, spawn::units::UnitType::C}},
  {"Zone Outdoor Air Wind Speed",{spawn::units::UnitType::m_per_s, spawn::units::UnitType::m_per_s}},
  {"Zone Outdoor Air Wind Direction",{spawn::units::UnitType::rad, spawn::units::UnitType::deg}},
  {"Zone Total Internal Radiant Heating Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Zone Total Internal Radiant Heating Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Total Internal Visible Radiation Heating Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Zone Total Internal Visible Radiation Heating Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Total Internal Convective Heating Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Zone Total Internal Convective Heating Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Total Internal Latent Gain Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Zone Total Internal Latent Gain Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Total Internal Total Heating Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Zone Total Internal Total Heating Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"People Occupant Count",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"People Radiant Heating Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"People Radiant Heating Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"People Convective Heating Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"People Convective Heating Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"People Sensible Heating Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"People Sensible Heating Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"People Latent Gain Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"People Latent Gain Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"People Total Heating Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"People Total Heating Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"People Air Temperature",{spawn::units::UnitType::K, spawn::units::UnitType::C}},
  {"People Air Relative Humidity",{spawn::units::UnitType::one, spawn::units::UnitType::percent}},
  {"Zone People Occupant Count",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Zone People Radiant Heating Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Zone People Radiant Heating Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone People Convective Heating Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Zone People Convective Heating Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone People Sensible Heating Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Zone People Sensible Heating Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone People Latent Gain Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Zone People Latent Gain Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone People Total Heating Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Zone People Total Heating Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Lights Electric Power",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Lights Radiant Heating Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Lights Radiant Heating Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Lights Visible Radiation Heating Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Lights Visible Radiation Heating Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Lights Convective Heating Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Lights Convective Heating Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Lights Return Air Heating Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Lights Return Air Heating Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Lights Total Heating Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Lights Total Heating Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Lights Electric Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Zone Lights Electric Power",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Lights Electric Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Zone Lights Radiant Heating Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Zone Lights Radiant Heating Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Lights Visible Radiation Heating Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Zone Lights Visible Radiation Heating Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Lights Convective Heating Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Zone Lights Convective Heating Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Lights Return Air Heating Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Zone Lights Return Air Heating Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Lights Total Heating Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Zone Lights Total Heating Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Electric Equipment Electric Power",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Electric Equipment Electric Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Electric Equipment Radiant Heating Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Electric Equipment Radiant Heating Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Electric Equipment Convective Heating Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Electric Equipment Convective Heating Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Electric Equipment Latent Gain Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Electric Equipment Latent Gain Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Electric Equipment Lost Heat Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Electric Equipment Lost Heat Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Electric Equipment Total Heating Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Electric Equipment Total Heating Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Electric Equipment Electric Power",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Electric Equipment Electric Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Zone Electric Equipment Radiant Heating Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Zone Electric Equipment Radiant Heating Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Electric Equipment Convective Heating Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Zone Electric Equipment Convective Heating Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Electric Equipment Latent Gain Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Zone Electric Equipment Latent Gain Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Electric Equipment Lost Heat Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Zone Electric Equipment Lost Heat Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Electric Equipment Total Heating Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Zone Electric Equipment Total Heating Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Windows Total Transmitted Solar Radiation Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Exterior Windows Total Transmitted Beam Solar Radiation Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Interior Windows Total Transmitted Beam Solar Radiation Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Exterior Windows Total Transmitted Diffuse Solar Radiation Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Interior Windows Total Transmitted Diffuse Solar Radiation Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Windows Total Heat Gain Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Windows Total Heat Loss Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Windows Total Transmitted Solar Radiation Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Zone Exterior Windows Total Transmitted Beam Solar Radiation Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Zone Interior Windows Total Transmitted Beam Solar Radiation Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Zone Exterior Windows Total Transmitted Diffuse Solar Radiation Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Zone Interior Windows Total Transmitted Diffuse Solar Radiation Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Zone Windows Total Heat Gain Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Zone Windows Total Heat Loss Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Surface Outside Normal Azimuth Angle",{spawn::units::UnitType::rad, spawn::units::UnitType::deg}},
  {"Surface Outside Face Sunlit Area",{spawn::units::UnitType::m2, spawn::units::UnitType::m2}},
  {"Surface Outside Face Sunlit Fraction",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Surface Outside Face Incident Solar Radiation Rate per Area",{spawn::units::UnitType::W_per_m2, spawn::units::UnitType::W_per_m2}},
  {"Surface Outside Face Incident Beam Solar Radiation Rate per Area",{spawn::units::UnitType::W_per_m2, spawn::units::UnitType::W_per_m2}},
  {"Surface Outside Face Incident Sky Diffuse Solar Radiation Rate per Area",{spawn::units::UnitType::W_per_m2, spawn::units::UnitType::W_per_m2}},
  {"Surface Outside Face Incident Ground Diffuse Solar Radiation Rate per Area",{spawn::units::UnitType::W_per_m2, spawn::units::UnitType::W_per_m2}},
  {"Surface Outside Face Beam Solar Incident Angle Cosine Value",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Surface Outside Face Incident Sky Diffuse Ground Reflected Solar Radiation Rate per Area",{spawn::units::UnitType::W_per_m2, spawn::units::UnitType::W_per_m2}},
  {"Surface Outside Face Incident Sky Diffuse Surface Reflected Solar Radiation Rate per Area",{spawn::units::UnitType::W_per_m2, spawn::units::UnitType::W_per_m2}},
  {"Surface Outside Face Incident Beam To Beam Surface Reflected Solar Radiation Rate per Area",{spawn::units::UnitType::W_per_m2, spawn::units::UnitType::W_per_m2}},
  {"Surface Outside Face Incident Beam To Diffuse Surface Reflected Solar Radiation Rate per Area",{spawn::units::UnitType::W_per_m2, spawn::units::UnitType::W_per_m2}},
  {"Surface Outside Face Incident Beam To Diffuse Ground Reflected Solar Radiation Rate per Area",{spawn::units::UnitType::W_per_m2, spawn::units::UnitType::W_per_m2}},
  {"Surface Anisotropic Sky Multiplier",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Surface Window BSDF Beam Direction Number",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Surface Window BSDF Beam Theta Angle",{spawn::units::UnitType::rad, spawn::units::UnitType::rad}},
  {"Surface Window BSDF Beam Phi Angle",{spawn::units::UnitType::rad, spawn::units::UnitType::rad}},
  {"Surface Window Total Glazing Layers Absorbed Solar Radiation Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Window Total Glazing Layers Absorbed Shortwave Radiation Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Window Front Face Temperature Layer 1",{spawn::units::UnitType::K, spawn::units::UnitType::C}},
  {"Surface Window Back Face Temperature Layer 1",{spawn::units::UnitType::K, spawn::units::UnitType::C}},
  {"Surface Window Transmitted Solar Radiation Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Window Transmitted Beam Solar Radiation Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Window Transmitted Beam To Beam Solar Radiation Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Window Transmitted Beam To Diffuse Solar Radiation Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Window Transmitted Diffuse Solar Radiation Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Window Heat Gain Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Window Heat Loss Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Window Gap Convective Heat Transfer Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Window Shading Device Absorbed Solar Radiation Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Window Net Heat Transfer Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Window Total Glazing Layers Absorbed Solar Radiation Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Surface Window Transmitted Solar Radiation Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Surface Window Transmitted Beam Solar Radiation Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Surface Window Transmitted Beam To Beam Solar Radiation Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Surface Window Transmitted Beam To Diffuse Solar Radiation Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Surface Window Transmitted Diffuse Solar Radiation Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Surface Window Heat Gain Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Surface Window Heat Loss Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Surface Window Gap Convective Heat Transfer Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Surface Window Shading Device Absorbed Solar Radiation Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Surface Window Net Heat Transfer Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Surface Window System Solar Transmittance",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Surface Window System Solar Reflectance",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Surface Window System Solar Absorptance",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Surface Window Inside Face Glazing Condensation Status",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Surface Window Inside Face Frame Condensation Status",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Surface Window Inside Face Divider Condensation Status",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Surface Window Outside Reveal Reflected Beam Solar Radiation Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Window Outside Reveal Reflected Beam Solar Radiation Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Surface Window Solar Horizontal Profile Angle",{spawn::units::UnitType::rad, spawn::units::UnitType::deg}},
  {"Surface Window Solar Vertical Profile Angle",{spawn::units::UnitType::rad, spawn::units::UnitType::deg}},
  {"Surface Window Glazing Beam to Beam Solar Transmittance",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Surface Window Glazing Beam to Diffuse Solar Transmittance",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Surface Window Glazing Diffuse to Diffuse Solar Transmittance",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Surface Window Model Solver Iteration Count",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Surface Inside Face Exterior Windows Incident Beam Solar Radiation Rate per Area",{spawn::units::UnitType::W_per_m2, spawn::units::UnitType::W_per_m2}},
  {"Surface Inside Face Exterior Windows Incident Beam Solar Radiation Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Inside Face Interior Windows Incident Beam Solar Radiation Rate per Area",{spawn::units::UnitType::W_per_m2, spawn::units::UnitType::W_per_m2}},
  {"Surface Inside Face Interior Windows Incident Beam Solar Radiation Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Inside Face Initial Transmitted Diffuse Absorbed Solar Radiation Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Inside Face Initial Transmitted Diffuse Transmitted Out Window Solar Radiation Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Inside Face Absorbed Shortwave Radiation Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Inside Face Exterior Windows Incident Beam Solar Radiation Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Surface Inside Face Interior Windows Incident Beam Solar Radiation Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Debug Surface Solar Shading Model DifShdgRatioIsoSky",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Debug Surface Solar Shading Model DifShdgRatioHoriz",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Debug Surface Solar Shading Model WithShdgIsoSky",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Debug Surface Solar Shading Model WoShdgIsoSky",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Surface Inside Face Temperature",{spawn::units::UnitType::K, spawn::units::UnitType::C}},
  {"Surface Inside Face Interior Movable Insulation Temperature",{spawn::units::UnitType::K, spawn::units::UnitType::C}},
  {"Surface Outside Face Temperature",{spawn::units::UnitType::K, spawn::units::UnitType::C}},
  {"Surface Inside Face Adjacent Air Temperature",{spawn::units::UnitType::K, spawn::units::UnitType::C}},
  {"Surface Inside Face Convection Heat Transfer Coefficient",{spawn::units::UnitType::W_per_m2_K, spawn::units::UnitType::W_per_m2_K}},
  {"Surface Inside Face Convection Heat Gain Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Inside Face Convection Heat Gain Rate per Area",{spawn::units::UnitType::W_per_m2, spawn::units::UnitType::W_per_m2}},
  {"Surface Inside Face Convection Heat Gain Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Surface Inside Face Net Surface Thermal Radiation Heat Gain Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Inside Face Net Surface Thermal Radiation Heat Gain Rate per Area",{spawn::units::UnitType::W_per_m2, spawn::units::UnitType::W_per_m2}},
  {"Surface Inside Face Net Surface Thermal Radiation Heat Gain Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Surface Inside Face Solar Radiation Heat Gain Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Inside Face Solar Radiation Heat Gain Rate per Area",{spawn::units::UnitType::W_per_m2, spawn::units::UnitType::W_per_m2}},
  {"Surface Inside Face Solar Radiation Heat Gain Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Surface Inside Face Lights Radiation Heat Gain Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Inside Face Lights Radiation Heat Gain Rate per Area",{spawn::units::UnitType::W_per_m2, spawn::units::UnitType::W_per_m2}},
  {"Surface Inside Face Lights Radiation Heat Gain Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Surface Inside Face Internal Gains Radiation Heat Gain Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Inside Face Internal Gains Radiation Heat Gain Rate per Area",{spawn::units::UnitType::W_per_m2, spawn::units::UnitType::W_per_m2}},
  {"Surface Inside Face Internal Gains Radiation Heat Gain Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Surface Inside Face System Radiation Heat Gain Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Inside Face System Radiation Heat Gain Rate per Area",{spawn::units::UnitType::W_per_m2, spawn::units::UnitType::W_per_m2}},
  {"Surface Inside Face System Radiation Heat Gain Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Surface Inside Face Conduction Heat Transfer Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Inside Face Conduction Heat Gain Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Inside Face Conduction Heat Loss Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Inside Face Conduction Heat Transfer Rate per Area",{spawn::units::UnitType::W_per_m2, spawn::units::UnitType::W_per_m2}},
  {"Surface Inside Face Conduction Heat Transfer Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Surface Outside Face Conduction Heat Transfer Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Outside Face Conduction Heat Gain Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Outside Face Conduction Heat Loss Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Outside Face Conduction Heat Transfer Rate per Area",{spawn::units::UnitType::W_per_m2, spawn::units::UnitType::W_per_m2}},
  {"Surface Outside Face Conduction Heat Transfer Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Surface Average Face Conduction Heat Transfer Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Average Face Conduction Heat Gain Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Average Face Conduction Heat Loss Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Average Face Conduction Heat Transfer Rate per Area",{spawn::units::UnitType::W_per_m2, spawn::units::UnitType::W_per_m2}},
  {"Surface Average Face Conduction Heat Transfer Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Surface Heat Storage Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Heat Storage Gain Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Heat Storage Loss Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Heat Storage Rate per Area",{spawn::units::UnitType::W_per_m2, spawn::units::UnitType::W_per_m2}},
  {"Surface Heat Storage Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Surface Inside Face Beam Solar Radiation Heat Gain Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Inside Face Convection Classification Index",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Surface Inside Face Convection Model Equation Index",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Surface Inside Face Convection Reference Air Index",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Surface Inside Face Heat Source Gain Rate per Area",{spawn::units::UnitType::W_per_m2, spawn::units::UnitType::W_per_m2}},
  {"Surface Outside Face Heat Source Gain Rate per Area",{spawn::units::UnitType::W_per_m2, spawn::units::UnitType::W_per_m2}},
  {"Surface Outside Face Outdoor Air Drybulb Temperature",{spawn::units::UnitType::K, spawn::units::UnitType::C}},
  {"Surface Outside Face Outdoor Air Wetbulb Temperature",{spawn::units::UnitType::K, spawn::units::UnitType::C}},
  {"Surface Outside Face Outdoor Air Wind Speed",{spawn::units::UnitType::m_per_s, spawn::units::UnitType::m_per_s}},
  {"Surface Outside Face Outdoor Air Wind Direction",{spawn::units::UnitType::rad, spawn::units::UnitType::deg}},
  {"Surface Outside Face Convection Heat Gain Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Outside Face Convection Heat Gain Rate per Area",{spawn::units::UnitType::W_per_m2, spawn::units::UnitType::W_per_m2}},
  {"Surface Outside Face Convection Heat Gain Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Surface Outside Face Convection Heat Transfer Coefficient",{spawn::units::UnitType::W_per_m2_K, spawn::units::UnitType::W_per_m2_K}},
  {"Surface Outside Face Net Thermal Radiation Heat Gain Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Outside Face Net Thermal Radiation Heat Gain Rate per Area",{spawn::units::UnitType::W_per_m2, spawn::units::UnitType::W_per_m2}},
  {"Surface Outside Face Net Thermal Radiation Heat Gain Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Surface Outside Face Thermal Radiation to Air Heat Transfer Coefficient",{spawn::units::UnitType::W_per_m2_K, spawn::units::UnitType::W_per_m2_K}},
  {"Surface Outside Face Thermal Radiation to Sky Heat Transfer Coefficient",{spawn::units::UnitType::W_per_m2_K, spawn::units::UnitType::W_per_m2_K}},
  {"Surface Outside Face Thermal Radiation to Ground Heat Transfer Coefficient",{spawn::units::UnitType::W_per_m2_K, spawn::units::UnitType::W_per_m2_K}},
  {"Surface Outside Face Thermal Radiation to Air Heat Transfer Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Outside Face Heat Emission to Air Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Outside Face Solar Radiation Heat Gain Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Surface Outside Face Solar Radiation Heat Gain Rate per Area",{spawn::units::UnitType::W_per_m2, spawn::units::UnitType::W_per_m2}},
  {"Surface Outside Face Solar Radiation Heat Gain Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Surface Outside Face Convection Classification Index",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Surface Outside Face Forced Convection Model Equation Index",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Surface Outside Face Natural Convection Model Equation Index",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Surface Shading Device Is On Time Fraction",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Surface Storm Window On Off Status",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Surface Window Blind Slat Angle",{spawn::units::UnitType::rad, spawn::units::UnitType::deg}},
  {"Zone Mean Radiant Temperature",{spawn::units::UnitType::K, spawn::units::UnitType::C}},
  {"Site Total Surface Heat Emission to Air",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Zone Mean Air Temperature",{spawn::units::UnitType::K, spawn::units::UnitType::C}},
  {"Zone Operative Temperature",{spawn::units::UnitType::K, spawn::units::UnitType::C}},
  {"Zone Mean Air Dewpoint Temperature",{spawn::units::UnitType::K, spawn::units::UnitType::C}},
  {"Zone Mean Air Humidity Ratio",{spawn::units::UnitType::one, spawn::units::UnitType::kgWater_per_kgDryAir}},
  {"Zone Air Heat Balance Internal Convective Heat Gain Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Air Heat Balance Surface Convection Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Air Heat Balance Interzone Air Transfer Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Air Heat Balance Outdoor Air Transfer Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Air Heat Balance System Air Transfer Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Air Heat Balance System Convective Heat Gain Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Air Heat Balance Air Energy Storage Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Exfiltration Heat Transfer Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Exfiltration Sensible Heat Transfer Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Exfiltration Latent Heat Transfer Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Exhaust Air Heat Transfer Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Exhaust Air Sensible Heat Transfer Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Zone Exhaust Air Latent Heat Transfer Rate",{spawn::units::UnitType::W, spawn::units::UnitType::W}},
  {"Site Total Zone Exfiltration Heat Loss",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Site Total Zone Exhaust Air Heat Loss",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Zone Thermal Comfort Fanger Model PMV",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Zone Thermal Comfort Fanger Model PPD",{spawn::units::UnitType::one, spawn::units::UnitType::percent}},
  {"Zone Thermal Comfort Clothing Surface Temperature",{spawn::units::UnitType::K, spawn::units::UnitType::C}},
  {"Zone Thermal Comfort Mean Radiant Temperature",{spawn::units::UnitType::K, spawn::units::UnitType::C}},
  {"Zone Thermal Comfort Operative Temperature",{spawn::units::UnitType::K, spawn::units::UnitType::C}},
  {"Zone Thermal Comfort ASHRAE 55 Simple Model Summer Clothes Not Comfortable Time",{spawn::units::UnitType::s, spawn::units::UnitType::hr}},
  {"Zone Thermal Comfort ASHRAE 55 Simple Model Winter Clothes Not Comfortable Time",{spawn::units::UnitType::s, spawn::units::UnitType::hr}},
  {"Zone Thermal Comfort ASHRAE 55 Simple Model Summer or Winter Clothes Not Comfortable Time",{spawn::units::UnitType::s, spawn::units::UnitType::hr}},
  {"Facility Thermal Comfort ASHRAE 55 Simple Model Summer Clothes Not Comfortable Time",{spawn::units::UnitType::s, spawn::units::UnitType::hr}},
  {"Facility Thermal Comfort ASHRAE 55 Simple Model Winter Clothes Not Comfortable Time",{spawn::units::UnitType::s, spawn::units::UnitType::hr}},
  {"Facility Thermal Comfort ASHRAE 55 Simple Model Summer or Winter Clothes Not Comfortable Time",{spawn::units::UnitType::s, spawn::units::UnitType::hr}},
  {"Zone Heating Setpoint Not Met Time",{spawn::units::UnitType::s, spawn::units::UnitType::hr}},
  {"Zone Heating Setpoint Not Met While Occupied Time",{spawn::units::UnitType::s, spawn::units::UnitType::hr}},
  {"Zone Cooling Setpoint Not Met Time",{spawn::units::UnitType::s, spawn::units::UnitType::hr}},
  {"Zone Cooling Setpoint Not Met While Occupied Time",{spawn::units::UnitType::s, spawn::units::UnitType::hr}},
  {"Facility Heating Setpoint Not Met Time",{spawn::units::UnitType::s, spawn::units::UnitType::hr}},
  {"Facility Cooling Setpoint Not Met Time",{spawn::units::UnitType::s, spawn::units::UnitType::hr}},
  {"Facility Heating Setpoint Not Met While Occupied Time",{spawn::units::UnitType::s, spawn::units::UnitType::hr}},
  {"Facility Cooling Setpoint Not Met While Occupied Time",{spawn::units::UnitType::s, spawn::units::UnitType::hr}},
  {"Schedule Value",{spawn::units::UnitType::one, spawn::units::UnitType::one}},
  {"Environmental Impact Electricity Source Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Environmental Impact Electricity CO2 Emissions Mass",{spawn::units::UnitType::kg, spawn::units::UnitType::kg}},
  {"Environmental Impact Electricity CO Emissions Mass",{spawn::units::UnitType::kg, spawn::units::UnitType::kg}},
  {"Environmental Impact Electricity CH4 Emissions Mass",{spawn::units::UnitType::kg, spawn::units::UnitType::kg}},
  {"Environmental Impact Electricity NOx Emissions Mass",{spawn::units::UnitType::kg, spawn::units::UnitType::kg}},
  {"Environmental Impact Electricity N2O Emissions Mass",{spawn::units::UnitType::kg, spawn::units::UnitType::kg}},
  {"Environmental Impact Electricity SO2 Emissions Mass",{spawn::units::UnitType::kg, spawn::units::UnitType::kg}},
  {"Environmental Impact Electricity PM Emissions Mass",{spawn::units::UnitType::kg, spawn::units::UnitType::kg}},
  {"Environmental Impact Electricity PM10 Emissions Mass",{spawn::units::UnitType::kg, spawn::units::UnitType::kg}},
  {"Environmental Impact Electricity PM2.5 Emissions Mass",{spawn::units::UnitType::kg, spawn::units::UnitType::kg}},
  {"Environmental Impact Electricity NH3 Emissions Mass",{spawn::units::UnitType::kg, spawn::units::UnitType::kg}},
  {"Environmental Impact Electricity NMVOC Emissions Mass",{spawn::units::UnitType::kg, spawn::units::UnitType::kg}},
  {"Environmental Impact Electricity Hg Emissions Mass",{spawn::units::UnitType::kg, spawn::units::UnitType::kg}},
  {"Environmental Impact Electricity Pb Emissions Mass",{spawn::units::UnitType::kg, spawn::units::UnitType::kg}},
  {"Environmental Impact Electricity Water Consumption Volume",{spawn::units::UnitType::m3, spawn::units::UnitType::L}},
  {"Environmental Impact Electricity Nuclear High Level Waste Mass",{spawn::units::UnitType::kg, spawn::units::UnitType::kg}},
  {"Environmental Impact Electricity Nuclear Low Level Waste Volume",{spawn::units::UnitType::m3, spawn::units::UnitType::m3}},
  {"Environmental Impact Purchased Electricity Source Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Environmental Impact Surplus Sold Electricity Source",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Environmental Impact Natural Gas Source Energy",{spawn::units::UnitType::J, spawn::units::UnitType::J}},
  {"Environmental Impact Natural Gas CO2 Emissions Mass",{spawn::units::UnitType::kg, spawn::units::UnitType::kg}},
  {"Environmental Impact Natural Gas CO Emissions Mass",{spawn::units::UnitType::kg, spawn::units::UnitType::kg}},
  {"Environmental Impact Natural Gas CH4 Emissions Mass",{spawn::units::UnitType::kg, spawn::units::UnitType::kg}},
  {"Environmental Impact Natural Gas NOx Emissions Mass",{spawn::units::UnitType::kg, spawn::units::UnitType::kg}},
  {"Environmental Impact Natural Gas N2O Emissions Mass",{spawn::units::UnitType::kg, spawn::units::UnitType::kg}},
  {"Environmental Impact Natural Gas SO2 Emissions Mass",{spawn::units::UnitType::kg, spawn::units::UnitType::kg}},
  {"Environmental Impact Natural Gas PM Emissions Mass",{spawn::units::UnitType::kg, spawn::units::UnitType::kg}},
  {"Environmental Impact Natural Gas PM10 Emissions Mass",{spawn::units::UnitType::kg, spawn::units::UnitType::kg}},
  {"Environmental Impact Natural Gas PM2.5 Emissions Mass",{spawn::units::UnitType::kg, spawn::units::UnitType::kg}},
  {"Environmental Impact Natural Gas NH3 Emissions Mass",{spawn::units::UnitType::kg, spawn::units::UnitType::kg}},
  {"Environmental Impact Natural Gas NMVOC Emissions Mass",{spawn::units::UnitType::kg, spawn::units::UnitType::kg}},
  {"Environmental Impact Natural Gas Hg Emissions Mass",{spawn::units::UnitType::kg, spawn::units::UnitType::kg}},
  {"Environmental Impact Natural Gas Pb Emissions Mass",{spawn::units::UnitType::kg, spawn::units::UnitType::kg}},
  {"Environmental Impact Natural Gas Water Consumption Volume",{spawn::units::UnitType::m3, spawn::units::UnitType::L}},
  {"Environmental Impact Natural Gas Nuclear High Level Waste Mass",{spawn::units::UnitType::kg, spawn::units::UnitType::kg}},
  {"Environmental Impact Natural Gas Nuclear Low Level Waste Volume",{spawn::units::UnitType::m3, spawn::units::UnitType::m3}},
  {"Environmental Impact Total N2O Emissions Carbon Equivalent Mass",{spawn::units::UnitType::kg, spawn::units::UnitType::kg}},
  {"Environmental Impact Total CH4 Emissions Carbon Equivalent Mass",{spawn::units::UnitType::kg, spawn::units::UnitType::kg}},
  {"Environmental Impact Total CO2 Emissions Carbon Equivalent Mass",{spawn::units::UnitType::kg, spawn::units::UnitType::kg}}
};

