name: Verify Pull Request Labeling

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  check_pr_labels:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Verify PR label action
        uses: mheap/github-action-required-labels@v1
        with:
          mode: minimum
          count: 1
          labels: "Defect, Refactoring, NewFeature, Performance, DoNotPublish"
